package me.rahulk.adtphaseshift2016;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ListView;

import java.util.ArrayList;

import me.rahulk.adtphaseshift2016.adapter.EventAdapter;


public class EventEvents extends Fragment {

    public EventEvents() {
        // Required empty public constructor
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View rootview = inflater.inflate(R.layout.fragment_event_events, container, false);
        ListView listView = (ListView) rootview.findViewById(R.id.lstEvent);

        final ArrayList<Event> eventArrayList = new ArrayList<>();

        // id, title, department, bmsce, regFees, prize1, prize2, venue, date, time, coordinator, coordinatorNumber, description
        eventArrayList.add(new Event(3,"Future Cities and Technology","Architecture",false,"50/Head","4000 INR","Nil","Architecture Studio","23rd Sep 2016","3 PM to 5 PM","Hamsa","8861115159","A Group event with maximum of 4 participants in a group, allowed to design their dream city. Materials will be provided."));
        eventArrayList.add(new Event(4,"Product Design","Architecture",false,"100/Group of 2","1000 INR","700 INR","Architecture Studio","24th Sep 2016","11 AM to 1 PM","Yashas N R","9008576055","2 Participants per group will have to design a composition on a tile or design a Furniture. Materials will be provided."));
        eventArrayList.add(new Event(5,"Picture This!","Architecture",false,"100/Head","1000 INR","700 INR","Architecture Studio","23rd Sep 2016","10 AM to 11 AM","Chamundeshwari","9886181603","Day 1: A brief introduction about the theme given to the participants on the day of the event.\n" + "Day 2: The participants are desired to submit their works by 12 PM and they are evaluated on the same day\n" + "Participants must get any devices that can be used to capture images with a minimum of 8 megapixels."));
        eventArrayList.add(new Event(6,"JIG Saw","Architecture",false,"100/Group of 4","1500 INR","1000 INR","Architecture Studio","23rd Sep 2016","2 PM to 4 PM","Chaitra U","9482860233","Team event which involves two parts.  First, the participants have to paint based on a given theme. Later, there will be an element of surprise. Materials to be brought by the participants. No. of participants – 4 per group"));
        eventArrayList.add(new Event(8,"TARDIS","Astronomy Club",false,"50/person","1000 INR","700 INR","PG 6004(EE)","23rd Sep 2016","11 AM to 1 PM","Ankith R","9731160844","Are you a capable of becoming a Time Lord and forgo all barriers and travel through space? Step into the TARDIS and experience the universe. The event will entail knowledge sharing of how IoT is used in space exploration and astronomy.\n" + "Rules:This quiz consists of three rounds . Total duration of the event is 90mins inclusive of all the three rounds.Cross College teams are allowed.No Use of Electronic Gadgets which otherwise will lead to disqualification. Teams of 2.\n" + "\n" + "Round 1- Initiation game: \n" + "Race time to solve puzzles related to the cosmos.(PS- A little grasp of TV series isn't so bad after all.) \n" + "Round 2-Guardians of the Galaxy\n" + "To be a guardian, you need to know the Galaxy like the back of your hand.(PS-Who knew recognising faces and patterns would come so handy? )\n" + "Round 3-Oblivion\n" + "Are you oblivious to everything happening around your world or are you really listening? Find out who is communicating to you by cracking the riddles."));
        eventArrayList.add(new Event(9,"ALLELES- a Biohunt!","Bioechnology",false,"100/person","1500 INR","700 INR","PG Block Biotech Department","23rd Sep 2016","12 PM to 5 PM","Priyank K","9035895423","Rounds include a clue to crack in each. It includes clues regarding various fields of biotechnology and life sciences. Skipping of rounds shall add a penalty to the team. Participants are required to get a smartphone."));
        eventArrayList.add(new Event(10,"Bio entertainment quiz","Bioechnology",false,"100/Team of 2","2000 INR","1000 INR","MV Hall","24th Sep 2016","2 PM to 5 PM","Devayani J","9535110569","Quiz combining pop culture and high  school biology.\n" + "Round 1-preliminary round \n" + "Round 2-final round, max of 10 teams will qualify."));
        eventArrayList.add(new Event(11,"Courtroom Genethics","Bioechnology",false,"100/Team of 2","1400 INR","700 INR","MV Hall","24th Sep 2016","9 AM to 12 PM","Hamsanandini","8861634539","Think animal testing is absolutely brutal? Or are you more inclined to believe that it's worth it if it saves human lives? Battle with your opinions on relevant cases in this classroom courtroom debate. \n" + "\n" + "- Individual event. \n" + "- Participants will be paired up. Each pair will be given an existing or fictional court case regarding bioethics- where one person will be the plaintiff and the other will be the defendant. They must then advocate for the cause of the entity they're representing.\n" + "- No Knowledge Of Biology Or Law Is Required. The participants will be judged on their reasoning skills and delivery. \n" + "- The case will be given on the day of the event, and the participants will be given   time to prepare.\n" + "-Further rules will be explained on the spot.\n" + "Topics for debates will include IoT.eg danger of smarter systems, RFID etc"));
        eventArrayList.add(new Event(13,"Rise of Mutants","Bioechnology",false,"150/Team of 3","1500 INR","700 INR","BT Classroom","24th Sep 2016","11 AM to 1 PM","Nihal K","7760284612","There will be two rounds. All scenarios must be explained scientifically. Each team will have 2-3 minutes to present their findings. Scoring will be done based on scientific accuracy and presentation skills. Participants need to get their own devices (smartphone, laptop) with internet access. Team of 3 members."));
        eventArrayList.add(new Event(14,"Start Up Wars","Bioechnology",false,"150/Team of max 3","1500 INR","1000 INR","BT Classroom","23rd Sep 2016","12 PM to 4 PM","Jonathan J","9632221994"," Ideating start up enterprises in the biotech field (pharma, agri, env, etc). \n" + "Max of 3 participants per team\n" + "All teams are to report at the allotted time where further details will be given\n" + "All teams will participate in all the rounds\n" + "Winners will be judged by points earned\n" + "Teams that have integrated IoT into their start up ideas will earn bonus points"));
        eventArrayList.add(new Event(15,"CHrash","Chemical",false,"100/Team of 2 or 3","1800 INR","1000 INR","PG CH-3001","23rd Sep 2016","12 PM to 2 PM","Nikitha","9916470865","Teams of 2 or 3.\n" + "Prelims: pen and paper test. Participants have to brainstorm and come up with solution to the set of engineering disaster related videos shown.\n" + "Final round: participants will be given to solve real time case on disasters and present their solution.\n" + "For both the rounds the final decision rests in the hands of judges."));
        eventArrayList.add(new Event(16,"Scifi battle","Chemical",false,"100/Team of 2","1400 INR","900 INR","PG CH-3001","24th Sep 2016","2 PM to 5 PM","Priyanka S","7795240104","Teams of 2 have to participate\n" + "There will be a preliminary round with elimination before the final round\n" + "Questions pertaining to IoT will be included\n" + "Questions can be posed in the form of logo identification and/or pictionary as well\n" + "Googling will lead to disqualification\n"));
        eventArrayList.add(new Event(17,"The Great mole relay race","Chemical",false,"100/Team of 4","1600 INR","800 INR","Outside Library Auditorium","24th Sep 2016","9 AM to 12 PM","Rashmita","7795645763","Group of 4.\n" + "1st round- 4 simple equations to be balanced. \n" + "2nd round- Enhanced stoichiometric questions including no. of moles, avogadro's number etc., for the equations given in 1st round. \n" + "3rd round- Picture quiz. \n" + "4th round- Crossword puzzle having clues for terminologies of IoT in Chemical Engineering industries.\n" + "Rules\n" + "Elimination- Teams completing the fastest in every round will be given the limited no. of batons (scrolls of questions for next round), leading to successive elimination\n" + "No mobile phones, smart watches and other electronic gadgets to be used during the race.\n" + "Dropping of baton leads to disqualification.\n" + "Scientific calculators without the covers can be used (brought by participants)"));
        eventArrayList.add(new Event(19,"Congrats! You're Placed.","Chemical",false,"100/person","1000 INR","800 INR","PG CH-3002","23rd Sep 2016","3 PM to 5 PM","Tanya Gopal","8095735719","The event depicts a mock placement process which consists of three rounds. The first round constitutes a general aptitude test: Basic yet Tricky. The second round is a Group Discussion on IOT in today's world , Current affairs and Challenges faced in the Industry. The final round is an interview / stress test conducted by an industrial person or a faculty member. The best candidate wins!"));
        eventArrayList.add(new Event(20,"CheMUN","Chemical",false,"100/person","1000 INR","800 INR","PG CH-3002","24th Sep 2016","12 PM to 3 PM","Avishek","9008796499","Formal debate protocols will be followed. No cross talking, address only to the chair. If you want to speak, raise the placard of your name and we will recognize you. Duration of the event will be 3 hours with a break in between The final decision will be by the judges discretion and cannot be challenged. The judging will based on the quality of the content, confidence of the speaker and body language while addressing"));
        eventArrayList.add(new Event(21,"The Sprinting Chemist","Chemical",false,"100/team of 3","1600 INR","800 INR","PG CH-6002","23rd Sep 2016","12 PM to 2 PM","Shireesh Gupta","8088804913","Team will be of 3 peoples. Each team will be assigned one starting element. A set of clues corresponding to locations in the college will be given. Every location will correspond to a compound or element.\n" + "Teams will have to go to the locations and write down the combinations they can make from the elements and compounds they already have. Teams will be informed in the sheet itself which clue will be leading to which element or compound so that they can preferentially solve clues depending on the elements and compounds they already have in their inventory from the starting element or from compounds collected by solving previous clues. \n" + "Time limit of 1 hour is decided. Team making maximum compounds will win."));
        eventArrayList.add(new Event(22,"Hunting with coordinates","Civil",false,"150/Team of 3","2000 INR","1500 INR","PG 7003","24th Sep 2016","11 AM to 2 PM","Sucharitha R","8884801014","Latitudes and longitudes shall be provided and participants will use GPS on their phones, reach that place and search for their next clue. Teams of 3."));
        eventArrayList.add(new Event(23,"Mixed Bag","Civil",false,"100/Team of 2","2000 INR","1500 INR","PG 7010","23rd Sep 2016","10 AM to 4 PM","Nishal S","8792522497","2 Rounds shall be conducted. Round 1- Case study (Topic will be given 3 days prior to the event and will be related to IoT in Civil engineering). Round 2-Quiz round (Questions related to IoT in civil engineering). Participants will be required to bring their laptops. Teams of 2."));
        eventArrayList.add(new Event(27,"IoT Code-A-Thon","Computer Science",false,"100/person","1500 INR","1000 INR","Internet Lab","23rd Sep 2016","11 AM to 4 PM","Karthik R","9741036752","Two rounds, each of 2 hours duration.\n" + "Participants will be given a problem set in the first round and will be asked to code their solutions on the computer provided.\n" + "Based on their performance, they will be selected for the second round.\n" + "In the second round, they will be given a harder problem set.\n" + "The participants with the best scores at the end of both rounds will win cash prizes\n" + "&; T-shirts by HackerEarth.\n" + "Participants will be allowed to code in C, C++ or Java."));
        eventArrayList.add(new Event(30,"IoT Ideathon","Computer Science",true,"200/team of 3 or 4","10000 INR","3000 INR","PG CS-5002","24th Sep 2016","2 PM to 5 PM","Govind","8971526662","Part I : Startup Sutra by Kedar Kulkarni\n" + "Kedar, CEO and founder of HyperVerge, will deliver an interactive talk on how HyperVerge started off in IIT Madras and went on to raise funding from the biggest VC firms in the Bay Area. The talk will cover different stages in the lifecycle of a startup, what one needs to do at each stage and what it takes to be an entrepreneur. He will also delve into the space of computer vision and how it can contribute in the IoT age.\n" + "Part II : Magic Share - PhaseShift Ideathon\n" + "Just like hackathons where groups of students work on hacking a project together in a short period of time, the Ideathon will be an open contest where the best minds of any background from different colleges (in groups of 3-4 per team) will work on generating innovative ideas on a real life problem statement (in the IoT space) in a short period of time. At the beginning of the competition, the problem statement will be released and teams will have one hour to play with the prototype/app/case, understand its working, suggest changes and generate new, creative ideas revolving around the problem statement. The merit of each submission will be judged based on the creativity of the ideas, feasibility and relevance."));
        eventArrayList.add(new Event(31,"IoT Tech Hunt","Computer Science",false,"Refer to rulebook","1500 INR","1000 INR","CSE Seminar Hall","24th Sep 2016","10 AM to 1 PM","Siddhartha","9454178342","Before the start of the event a brief tutorial on how to code on an Arduino board will be given to the participants.\n" + "Details:\n" + "An encrypted key that reveals a location in the CS/TC block is given to each group.\n" + "On successfully decrypting the key, a location will be obtained. At this location a sequence or a task that must be completed on an Arduino Board will be given.\n" + "Once the task is completed successfully, the next encrypted location will be given to the group.\n" + "The group to cover maximum locations/finish the entire course at the end of 2\n" + "hours will win the event."));
        eventArrayList.add(new Event(32,"Tech JAMboree","Computer Science",false,"100/person","1000 INR","700 INR","PG CS-5003","23rd Sep 2016","10 AM to 1 PM","Apoorva S","7760600390","Round 1: Tech Taboo - Participants will be put into groups of four and each participant will have to get their team members to guess the word written on their card sheet without using the four other clue words specified on their card. Each Participant will get one minute to get maximum word guesses. 3 Teams with maximum word guesses will qualify to the second round.\n" + "Round 2: Jargon Jam - Now each participant will compete with the other three members in the team in an intensive round of JAM (Just A Minute). Each group of four contestants will be given a minute to talk on any debatable topic regarding current trends in technology, and each contestant must &quot;JAM &quot; or buzz the current speaker in case of a)Repeating ideas, b)Stating contradictory opinions as his/her own, c) Speech errors such as stammering etc. A successful JAM or buzz will result in the caller of the JAM now becoming the speaker. Points will be awarded based on the time each contestant spoke for, and the number of accurate JAMS. 4 top scoring participants will move on to the final round.\n" + "Round 3: System Crash: All the participants will be given a common problem scenario and a unique collection of devices that he/she has at his/her disposal. They must come up with a solution using Internet of Things using the devices given to them, and pitch their ideas to the judges, explaining why their idea would be the best idea to prevent a “System Crash” \n"));
        eventArrayList.add(new Event(33,"Techzibition","Computer Science",false,"200/person","1500 INR","1000 INR","CR-104","24th Sep 2016","10 AM to 4 PM","Sumedha","9663523435","Provides a platform for budding innovators and creators to present their ideas and projects related to IoT.\n" + "The event is categorized into 2:\n" + "1. Idea based\n" + "2. Prototype based.\n" + "\n" + "Participants can participate in either category and they will be evaluated separately.First & Second prizes will be given in each category.\n" + "Participants should get:\n" + "Presentation - if the participants are proposing an idea.\n" + "Presentation and prototype if they have the product implemented.\n"));
        eventArrayList.add(new Event(35,"ABB Makethon","Electrical and Electronics",false,"200/Team of 4","5000 INR","3000 INR","Measurements Lab","23rd Sep 2 PM to","24th Sep 2 PM","Anirudh","9448496283",""));
        eventArrayList.add(new Event(37,"Bomb Diffusion 3.0","Electrical and Electronics",false,"100/Team of 2","1500 INR","1000 INR","PG EE-6002 and PE Lab","23rd Sep 2016","12 PM to 3 PM","Uma R","8884322997","The preliminary round will have a written test on analog and digital electronics circuits. The teams qualifying for the next round/s shall be given incomplete/incorrect circuits which have to be debugged or completed to get the expected output in the shortest time. In collaboration with Circuit Challenge.\n"));
        eventArrayList.add(new Event(40,"Electro Blitz","Electronics and Communication",true,"150/Team of 3","3000 INR","1500 INR","EC 203 and AEC lab, EC block","24th Sep 2016","10 AM to 4 PM","Nikitha N","9008858220","Teams will be subjected to rounds which will test their theoretical, practical and logical understanding of electronics at different difficulty levels.\n" + "• Teams of 3\n" + "• Teams only from BMSCE are allowed to participate.\n" + "• Participants with valid ID cards of their respective institutions are eligible\n" + "• Prerequisites include knowledge of basic electronics\n" + "Round 1: WORDSWORTH\n" + "A set of letters will be displayed on the screen using which the teams will have to frame as many words as possible in a time limit of 15 mins. The words should be related to the theme IoT.\n" + "Round 2: KNOW THE UNKNOWN\n" + "Teams will be given set of codes. They will have to decode each code to get a name of a component (like Bluetooth). Once they get all the components names they will be provided with one more code. On decoding that they will get the name of an IoT system. They should draw a block diagram using the components that they have, to form the given system. Clues are given at the cost of points obtained in previous round. Top 4 teams which finish the task will be qualified for the next round.\n" + "Round 3: TAG YOUR PARTNER\n" + "Each team will be assigned a circuit. One from each team will design it and tag his/her mate who then rigs it up. The last teammate will have to power on the circuit and get correct outputs.Absolutely no form of communication is allowed among the teammates."));
        eventArrayList.add(new Event(43,"Escape If You Can","Electronics and Communication",false,"150/ team of 3","3000 INR","1500 INR","EC block 2nd floor","23rd Sep 2016","9 AM to 5 PM","Anjana","9035070780","Teams have to perform various tasks like algorithm design, coming up with block diagrams for smart things and solving puzzles while manage their teamwork and time. Teams must consist of 3 students. All students with a valid identity card of their respective educational institutes are eligible to participate. Teams from different colleges can form a team. In case of disputes, judges decision will be final.\n" + "Round 1: The Road Not Taken\n" + "1. Find a path from the start to finish line.\n" + "2. The path will have components pertaining to IoT devices and also symbols of trending IoT terminologies.\n" + "3. Use the shortest path or collect more components along the path, scores will vary.\n" + "Round 2: Do you have it all?\n" + "1. Based on the game of sets\n" + "2. The objective is to complete the flow diagram of a given IoT application.\n" + "3. Each team has 5 passes.\n" + "4. You can use extra passes at 50 points each, if you get another team to trade cards with you (there will be a risk of the team not having the card you want) or use your own blocks.\n" + "5. Finally, get the whole block diagram.\n" + "Round 3: Prison Break\n" + "Each person in the team will have a specific task in this room. One person will be blindfolded and will be guided by the second teammate to reach the place where the clues are placed. The third person in the team is the solver, who has to solve the clues.\n" + "Roles can’t be switched during the course of the game. Maximum time limit is 20 minutes. The first team to efficiently solve all the clues will get the key.\n" + "Clues will be based on IoT and Basic Electronics."));
        eventArrayList.add(new Event(44,"Fury Road v2.0","Electronics and Communication",false,"150/team of 4","4000 INR","2000 INR","PG Block 1st Floor","24th Sep 2016","9 AM to 5 PM","Heethesh","9611122852"," A team may consist of a maximum of 4 Members. Cross-college teams are allowed.\n" + "About the Event: \n" + "The aim of this event is to design and build a single remote controlled car that can compete in various challenges such as a Maze, a Football Match and an Obstacle Course. Teams must build their OWN RC Car for this event. \n" + "A workshop on building RC Cars will be conducted for all registered participants during the second week of September at BMSCE. The details of the workshop will be communicated to all the registered participants soon. Laptop, Soldering Iron, Batteries must be brought by the participants.\n" + "General Rules:\n" + "The maximum dimensions of the RC Car should be within 13cm (width) x 20cm (length). Robot must be controlled manually via wireless communication (Eg: Bluetooth, Radio). The event consists of three rounds:\n" + "Round 1 – Temple Run: Teams are required the complete a given maze and collect a maximum number of coins within a given time period. The maze will be a flat arena with bricks placed as walls. Top scoring teams will be qualified for the next round.\n" + "Round 2 – Football Knockouts: Teams will have to score goals in a match of football, using the same RC Car. The game will consist of two halves each of 5 minutes duration. The winners of each match will be qualified for the next round.\n" + "Round 3 – Death Race: This final round will consist of an obstacle course where all finalists will race simultaneously to cross the finish line. Winners of this round will be declared as the winners of this event."));
        eventArrayList.add(new Event(45,"Mega Mind","Electronics and Communication",false,"150/Team of 3","3000 INR","1500 INR","EC 202, AEC Lab","23rd Sep 2016","9 AM to 5 PM","Srinivas S","8884171828","The event comprises of three rounds in which, the first round shall be a written round and the other two shall be hardware-based rounds. The fastest of them all who can maintain accuracy takes home the prize!!.\n" + "• A team must consist of three participants. Inter-collegiate teams shall be allowed.\n" + "   Round 1: Roll And Don’t Stroll\n" + "• Questions of varying difficulty levels are distributed into different sets.\n" + "• The teams roll a die and the number decides the difficulty level of their question set.\n" + "• 40% of the questions in this round will pertain to IoT and Wireless Communication.\n" + "• Each team will be given a maximum of 30 minutes to answer the set.\n" + "   Round 2: Ready Set Glow\n" + "• Each problem will involve a circuit, corresponding to a question, in which a component which uniquely completes the circuit will be missing.\n" + "• The teams will have to connect the correct black box which will answer the question and complete the circuit.\n" + "• 40% of the questions in this round will be related to IoT and Cloud computing.\n" + "Round 3: Rectifier\n" + "• Each team will be given a pre-constructed circuit which contains unwanted and redundant components.\n" + "• The team will have to first identify the working of the circuit, and then optimize it by identifying and removing dispensable components without affecting the circuit’s functioning. For each component removed, they get a block of an IoT circuit. These blocks must be put together to get a complete IoT circuit.\n"));
        eventArrayList.add(new Event(46,"Online Questionnaire (IEEE)","Electronics and Communication",false,"50/person","1000 INR","500 INR","Online","nan","nan","Rishab","7760534154","This is an individual event that consists of complex questions under the following 5 domains:-\n" + "1) IoT and wireless networks.\n" + "2) Digital Signal Processing & Microcontrollers\n" + "4) RF / Microwaves / Antennas / Waveguides\n" + "5) Analog, Digital and Computer Communication\n" + "6) Analog  and Digital electronics / Digital IC’s\n" + "The questions could be MCQs or subjective.\n" + "The event will be hosted online on a portal which will be made available to the participants by mail. The portal will be opened at 7pm on 23/09/2016 and will be closed at 11pm.\n" + "All participants who have registered online for the event must mail a scanned copy of their ID card to the event co-ordinator (rishab9996@gmail.com)"));
        eventArrayList.add(new Event(47,"Short Movie Making","Electronics and Communication",false,"150/Team of 4-6","3000 INR","1500 INR","EC 201","23rd Sep 9 AM to","24th Sep 3 PM","Faraz Khan","8050332624","Teams have to showcase their creativity in short video to capture the importance of technology.\n" +
                "A team may consist of a maximum of 4-6 participants. Students from different educational institutes can form a team. \n" +
                "All students with a valid identity card of their respective educational institutes are eligible to participate. Teams are allowed to use any media for recording and editing. Teams will have to bring their own equipment. In case of disputes, judge’s decision will be final. Video Recording\n" +
                "Device, Laptop with editing software must be brought by participants.\n" +
                "General Instructions:\n" +
                "The reference video will be sent to their respective mails and will be informed on phone. The video can’t be a montage, slide show movie.\n" +
                "Judges decision will be final.\n" +
                "Gameplay:-\n" +
                "Round 1: Remakedaaa!\n" +
                "In this round, all participating team will be given a reference video, which they need to remake. The reference video will be released to all participants 5-6 days before the event. The finished. Remake should be based on the theme IoT. All videos will be screened on day 1 and 6 teams will be selected for 2nd round.\n"));
        eventArrayList.add(new Event(48,"Abstrakt It!","BMSCE IEEE",false,"100/person","1000 INR","700 INR","PG block EC-6001","23rd Sep 2016","10 AM to 1 PM","Vidhya T","9663740919","IoT related IEEE paper will be provided with title and abstract covered printed on page.\n" +
                "Participants have to read the paper and write the abstract and title in the best possible way (30 minutes)."));
        eventArrayList.add(new Event(50,"Paper Presentation","BMSCE IEEE",false,"IEEE meTeams of 1-4","3500 INR","2500 INR","BSN Hall","24th Sep 2016","9 AM to 2 PM","Tarun Verma","7406323829","It should be 2-6 pages long PDF manuscript in IEEE conference format. All the papers will be peer reviewed. The paper should have an original idea, implementation, simulation and experimentation. The IEEE plagiarism policy is applicable to all submissions. \n" +
                "Selected papers will be published in journals.\n" +
                "Last date of Submission: 16th Sep 2016\n" +
                "The presentation of accepted papers will be on day of Phase Shift.\n" +
                "Each author of the accepted paper will get a participation certificate."));
        eventArrayList.add(new Event(51,"Ad-Apt","Insustrial Engineering & Management",false,"100/Team of 3-4","1500 INR","1000 INR","CIM Lab (IEM DEPT)","23rd Sep 2016","11 AM to 5 PM","Hansa N","8951621517","Teams of 3-4 are allowed. In first round the teams have to market certain products to a target audience within the campus. According to the marketing skills, the audience will give the teams fake currency. The top 4 teams with the most ‘money’ will progress to the second round. In the second round, the teams will be given a failed product which they have to make “smart” using IoT and sell. (Basic IoT briefing will be given)."));
        eventArrayList.add(new Event(52,"Ez-Rider (geared)","Insustrial Engineering & Management",false,"50/person","1500 INR","1000 INR","Gopi wall/Mechanical parking lot","23rd Sep 2016","11 AM to 5 PM","Nikhil J","7406495475","Participation is allowed only upon the production of a driver's license (photocopies or soft copies are accepted). Participants are not allowed to take part in the event with their own vehicle. Both for girls and boys. Participants must navigate through an obstacle course on a geared vehicle. They should not keep their feet on the ground. Time penalty of +3 seconds each time they place their feet on the ground. Time penalty of +5 seconds for collision with obstacles. Whoever finishes the course in the shortest time wins. Sensor will be fitted to the vehicle to measure the time."));
        eventArrayList.add(new Event(53,"Ez-Rider (non geared )","Insustrial Engineering & Management",false,"50/person","1500 INR","1000 INR","Gopi wall/Mechanical parking lot","24th Sep 2016","11 AM to 5 PM","Pratik R","7829000373","Only for girls(boys who do not know geared). Participants must navigate through an obstacle course on a MOPED(gearlesss vehicle). They should not keep their feet on the ground. Time penalty of +3 seconds each time they place their feet on the ground. Time penalty of +5 seconds for collision with obstacles. Whoever finishes the course in the shortest time wins. Sensor will be fitted to the vehicle to measure the time."));
        eventArrayList.add(new Event(54,"Materialistic","Insustrial Engineering & Management",false,"100/Team of 2-3","1500 INR","1000 INR","IEM CR1 (Mech block 1st floor)","24th Sep 2016","11 AM to 4 PM","Apoorva","9740041642","Team of 2/3. Round 1: Jenga , game based on structures. Round 2:Connect , Derive answer from three related pictures. Round 3: Junkart , build useful items with provided junk. Jenga sets as well as junk will be provided. Internet usage permitted only for answering. Participants need to have a mobile phone with working data connection."));
        eventArrayList.add(new Event(55,"PANIC!","Insustrial Engineering & Management",false,"150/Team of 3 or 4","2000 INR","1000 INR","ERP LAB, TAYLOR HALL, IE Lab","23rd Sep 2 PM to","24th Sep 5 PM","Pranab D","9902103103","Round 1 : Geoguessr www.geoguessr.com\n" +
                "Uses google streetview to drop you off at a random location on earth. You need to navigate to find clues about your location. Then after gathering intel, make an educated guess on the map. The closer you are to your actual location, The more points you get. Max 5000 per round. 5 rounds.Team of 3 or 4. (Left to their choice).2 people per team allowed inside lab.Each team given link for the same 5 locations. Points are added to or subtracted from the total score if they finish the challenge within the given time, or use the internet to google.\n" +
                "Within 15 minutes : +5000 points\n" +
                "Within 20 minutes : +4000 points\n" +
                "Within 25 minutes : +3000 points\n" +
                "Google once  : -1000 points\n" +
                "Google twice : -5000 points\n" +
                "Each team is allowed to Google only once per round, with a maximum of 2 lifelines allowed per team.Time limit for the first round is 30 minutes.\n" +
                "Round 2 : Escape Room \n" +
                "The top 5 teams from the previous round will be selected. Each team will be locked into the room. Solving each clue will lead to the next. Upon solving the final clue, a password is revealed. They must use this password to escape from the room. The theme is \" Bank Heist\". Each team will start from within the bank and try to break into the safe. A rare artifact in the safe is what the teams are after. Time will be added for utilizing lifelines. The two quickest teams to escape the room wins."));
        eventArrayList.add(new Event(57,"IOT Intelligence","Information Science",false,"120/Team of 2","3000 INR","1000 INR","ISE Lab (EC block)","23rd Sep 2016","9 AM to 2 PM","T Mithun","9535262771","A gruelling team coding event where participants are given real life IoT problems and a coding solution is expected from them. Participants are expected to enter in teams of 2.\n" +
                "Preliminary round – Walk-in any time from 9am - 2pm to an open round where an IoT problem is given to the participants and they are expected to give a solution, but they are timed. The fastest 15 teams progress to round 2.\n" +
                "Second Round – A common problem is given to the 15 teams. Fastest 7 will be selected for final round.\n" +
                "Final round – A common problem is given to the remaining teams. The quickest team to solve will be declared the winner."));
        eventArrayList.add(new Event(58,"Logo Mania 3.0","Information Science",false,"50/person","3000 INR","1000 INR","PG block IS-4001","23rd Sep 2016","11 AM to 2 PM","Rayapeddi","8095372333","The most awaited event with highest participation is here, put your logo quiz (the game you play in class) skills to test, at Phase Shift; with a IoT based logo mania.\n" +
                "Preliminary memory round – A written quiz is given. It will have 30 logo based questions. Top 40 participants will be selected for the second round. \n" +
                "Second round – A slide containing 80 logos will be shown to the participants for 30-40 seconds. Soon after, the participants should write down as many logos they can remember.  Top 15 will be selected for final round. \n" +
                "Final round – A logo based quiz, which is conducted by a quiz master. The participants are expected to answer. The best participant will be declared winner."));
        eventArrayList.add(new Event(59,"Route IT","Information Science",false,"100/Team of 2","3000 INR","1000 INR","PG block IS-4004","24th Sep 2016","10 AM to 2 PM","Nataraj","9739646185","Is an exciting team treasure hunt event modelled after recent sensation Pokémon Go.Participants are expected in teams of 2 students each.\n" +
                "Preliminary round – A basic IoT quiz is conducted. Top 20 teams progress to round two.\n" +
                "Second round - 50 QR code Posters are scattered around the campus of BMSCE, the top 10 teams to find as many of these codes and retrieve passwords after scanning them, proceed to final round.\n" +
                "Final Round - 5 private network routers to be placed in various spots around campus.\n" +
                "The teams are then set off on a password hunt, 5 at a time.The teams are given a beginning router name, which they will have find and solve a small puzzle to find the password and next router name.The Fastest team to retrieve 3 consecutive passwords wins."));
        eventArrayList.add(new Event(63,"InQUIZitive","MBA",false,"100/Team of 2","3000 INR","2000 INR","PG block 3rd floor - MBA classroom 1","24th Sep 2016","11 AM to 1 PM","Sannidhi","7406678375","This is a business quiz event which will test the participant’s knowledge about various aspects of business and  related issues including IoT based business.\n"));
        eventArrayList.add(new Event(64,"Business Plan Competition","MBA",false,"100/Team of 2","2000 INR","1000 INR","MBA Finance class(PG block 3rd floor)","23rd Sep 2016","11 AM to 1 PM","Pawan A","9738644173","Participants would be proposing a business plan based on the theme IoT. The outcomes include Idea Generation to Launch - Feasibility of the plan.\n" +
                "\n" +
                "Last date for registration is 19 th September 2016. NO SPOT REGISTRATIONS.\n" +
                "All the registered participants will be updated on 19 th September 2016."));
        eventArrayList.add(new Event(65,"Ad making","MBA",false,"100/Team of 2","2000 INR","1000 INR","MBA classroom 2(PG block 2nd floor)","23rd Sep 2016","2 PM to 4 PM","Ranjith","9902264822","Participants will be shooting a video ad about the theme IoT.\n" +
                "\n" +
                "Last date for registration is 19 th September 2016. NO SPOT REGISTRATIONS.\n" +
                "All the registered participants will be updated on 19 th September 2016.\n"));
        eventArrayList.add(new Event(66,"Block and tackle","MBA",false,"50/person","2000 INR","1000 INR","PG block 3rd floor - MBA Finance class","24th Sep 2016","2 PM to 4 PM","Prannay","9886099624","Block and tackle puts participants in situations where they have to contradict their own opinion on many issues including IOT."));
        eventArrayList.add(new Event(67,"Ideas Galore","MCA",false,"100/Team of 2","1500 INR","1000 INR","Computer Applications classroom-4","23rd Sep 2016","2 PM to 4 PM","Abhishekkappa","8722661138","Poster presentation themed “SMART CITIES” expects participants to present the ideas to provide innovative, implementable and cost effective solutions for transportation, infrastructure, and water management system in Indian cities.2 in a team.\n" +
                "Phase I:\n" +
                "Submission of presentation should be done using ACM template.\n" +
                "Poster size is A3\n" +
                "Participates should send their posters before 19 th September 2016 to ideasgalore2016@gmail.com\n" +
                "All the submitted ideas will be evaluated by judges and top 10 teams will be shortlisted for Round 2.\n" +
                "\n" +
                "Phase II:  Presenting the poster in front of the judge and top 2 teams will be awarded."));
        eventArrayList.add(new Event(69,"Code Storm","MCA",false,"150/Team of 2","2000 INR","1000 INR","MCA Lab","23rd Sep 2016","11 AM to 1 PM","Harish R","9611261166","IoT is the network of interconnected devices or things with sensors embedded, software, network connection and necessary electronics that enables them to collect and exchange data enabling responsiveness.Code storm event is about implementing use cases of IoT using “Raspberry Pi” board, sensors and personal computers.\n" +
                "Rules:\n" +
                "Team of 2.\n" +
                "Three rounds: Every round will be an elimination round. In Each round a single problem is defined to all the teams. The teams should come up with solutions. Based on the timing and the efficiency of the solution, the team advances to the next round. Two of the teams based on their performance in the final round will be awarded.\n" +
                "Any of the programming language can be used."));
        eventArrayList.add(new Event(70,"Project Emblazon","MCA",false,"100/person","1500 INR","1000 INR","ICL lab","24th Sep 2016","11 AM to 1 PM","Anil K","9739280907","Demonstration of  IoT project developed by the participant. Participants must get their project material for demonstration. Project should be demonstrated in front of the judge."));
        eventArrayList.add(new Event(71,"Assemble Me","Mechanical Engineering",false,"200/Team of 2","1500 INR","1000 INR","CAED LAB Mechanical department","23rd Sep 2016","11 AM to 1 PM","Suraj S","9916052713","Contestants must know SOLID Edge software. Parts to be designed and assembled will be having the theme of IOT. The parts will contain sensors and actuators shown as different shapes which form an integral part of IOT. \n" + "Participants will be given the task of modeling these shapes and assembling them to obtain a system that can perform specific function. Teams of 2."));
        eventArrayList.add(new Event(72,"Best Mechanic","Mechanical Engineering",false,"300/Team of 4","1500 INR","1000 INR","Som Lab (Mech block)","23rd Sep 2016","3 PM to 5 PM","Shubam","8088439668","The event consists of a single round where a team of 4 members are supposed to assemble the parts of an object given. The thing which has to be assembled will be said at the time of the event. Example: a car, an automotive part etc. They are supposed to assemble within the given time. The team which finishes first wins. All the components are provided by us. If they ruin any of the part, it will not be provided again. At the end of the event, the object they assemble should work properly. The model they make when connected to a controller, should work when controlled from any location using the process of IoT."));
        eventArrayList.add(new Event(73,"Junkyard Javelin","Mechanical Engineering",false,"300/Team of 2","1500 INR","1000 INR","nan","nan","nan","Ajay S M","9480413996","This Event Requires the Participants to construct a Throwing Mechanism from the given Junk to throw a ball, the range being the deciding factor to get a winner.We are integrating IOT and Junkyard Javelin by making use of iot based measuring system (Sonar being used in this case). This will measure the distance traversed by the ball, process it and calculate the initial velocity of the ball by taking in the Release angle as input. All teams will get 3 chances with the farthest out of the three considered for getting a winner.In case of a tie, the one with the highest sum of the 3 chances combined wins. No Slingshots allowed."));
        eventArrayList.add(new Event(74,"BOT WARS","Mechanical Engineering",false,"400/Team of max 4","4000 INR","Nil","MPH","24th Sep 2016","2 PM to 4 PM","Ayush k","9620628571","Multiple robots battling among themselves for the survival within the arena. Various rounds will be conducted based on the number of participants. Participants will be asked to submit their robot specs with pictures two day prior to the event which will be further updated on the Facebook page for strategic discussions. Participants have to get required robots and materials. Robot which is unable to move even after 30 sec after damage loses. The dimensions of the robot are 2ftx1ftx1ft."));
        eventArrayList.add(new Event(75,"Utility Chain","Mechanical Engineering",false,"Refer rulebook","1500 INR","1000 INR","Mechanical workshop","23rd Sep 2016","11 AM to 3 PM","Anand M","7204216379","In 1st round, the competitors will have to make the specific model using workshop tools. To include IoT into the event, we will have one die for a model in which the model of the competitor should fit in. If the model fits in the sensor should indicate it by glowing lights.\n" +
                "In 2nd round, a presentation on problems utility chain management with iot solutions. Participants must participate in both rounds."));
        eventArrayList.add(new Event(77,"Criminal Case 3.0 : CYBER","Medical Electronics",false,"400/Team of 4","2000 INR","1000 INR","Medical Electronics Department","24th Sep 2016","2 PM to 5 PM","Madhusudana H J","9741335084","Think your team can solve the crime better than Sherlock and Watson? Beat your competitors to solve a mystery filled criminal case!\n" +
                "\n" +
                "\n" +
                "Round 1: Make use of all the random pieces of information you've gathered over the years about computers and IOT to solve a crossword in a given time frame to move to the next round.\n" +
                "Round 2: Analyse the crime scenes and come up with a list of what could be clues to find the root cause of the series of disasters.\n" +
                "Round 3: Solve the crime. Yes, it's that simple.\n" +
                "\n" +
                "1)4 participants in a team.\n" +
                "2)15 teams will move on to round two. In case of ties, a tie breaker round will be conducted for which the rules will be given on spot.\n" +
                "3)6 teams will move on to the final round.\n" +
                "4)The participants shall not procure help from anyone not in their team and no usage of cell phones."));
        eventArrayList.add(new Event(78,"Mystery Inc.","Medical Electronics",false,"200/Team of 2","2000 INR","1000 INR","Medical Electronics Department(5th floor,PG Block)","23rd Sep 2016","2 PM to 4 PM","Vinutha","9741058711","2 participants per team.The event requires basic understanding of electrical, electronics and IoT concepts to solve the given problems.Usage of any electronic devices or taking outside help is NOT allowed.\n" +
                "\n" +
                "\n" +
                "Round 1- A written round where the participants will have to answer puzzles and solve riddles fast enough to move onto the next round.\n" +
                "Round 2- A round where top 10 teams from the previous round will be selected to solve the clues leading them to the next successive location. In the end, they will have to answer the given questions correctly to be given the components for the next round.\n" +
                "Round 3- 5 top teams from the previous round will be selected to complete the IoT based circuit and implement it."));
        eventArrayList.add(new Event(79,"Cimeathon","Medical Electronics",true,"100/person","Refer rule book","Refer rule book","PG block 5th floor ML dept","23rd Sep 2016","9 AM to 5 PM","Vinutha","9986618110","The Hackathon will convene the interdisciplinary students from different disciplines over a period of 8 hours on Medical IOT in order to develop innovative ideas/prototype solutions (hardware/software) to address healthcare challenges of in India.\n" +
                "Rules of the Hackathon:\n" +
                "The participants should work on one of the themes mentioned above during the above said hackathon.\n" +
                "Team Formation: Teams should have members with a mix of different technical background. You are welcome to form teams beforehand. But we do encourage to form the team at the start of the event so that you could really have a force of Multidisciplinary learning.\n" +
                "Resources: Participants in the hackathon can carry any materials with them related to the hackathon. For the Hackathon, participants are requested to carry their laptops. Wi-fi would be provided for all participants.\n" +
                "Mentorship: The team would get access to plethora of mentors who have expertise of clinical, technical, business, designing, etc.\n" +
                "Partners: Ellipsonic, Philips, InnAccel, Villgro Foundation \n" +
                "Prizes for winners: Cash prize upto 25,000 INR "));
        eventArrayList.add(new Event(80,"Confoundo 2.0","Pentagram",false,"100/ Team of 2","1500 INR","1000 INR","PG block CS-5005","23rd Sep 2016","10 AM to 12 PM","Vivek","7022150431","Confound your senses by taking our maths quiz. Answer the question to score points.Answers to questions will be in encrypted form and the teams have to decode it to get the required IOT term.\n" +
                "3 Rounds:\n" +
                "1st Round: A set of questions will be provided to the teams. The top 6 teams will qualify for the next round.\n" +
                "2nd Round: Buzzer Round. The team which answers the question first correctly gets the point.\n" +
                "3rd Round: Final face-off between top two teams."));
        eventArrayList.add(new Event(81,"Gridlock 2.0","Pentagram",false,"100/Team of 2","1500 INR","1000 INR","PG block CS-5005","23rd Sep 2016","2 PM to 4 PM","Sharada","8762666076","Single Round event. You will be given a paragraph containing clues.The paragraph will be loosely based on IOT. With the help of clues , you have to arrange data in a grid.The answer to the proceeding question will help you unravel the next."));
        eventArrayList.add(new Event(82,"Biz-Tech Quiz","Quiz",false,"100/Team of 3","6000 INR","3000 INR","Indoor Stadium","24th Sep 2016","9 AM to 1 PM","Rahul S","7829076699","A quiz having everything from the world of business and technology. The quiz tracks business and technology trends through history till the cutting edge technologies like IoT,cyber systems etc. helping participants gain the perspective of businesses across the world."));
        eventArrayList.add(new Event(83,"General Quiz","Quiz",false,"100/Team of 4","6000 INR","3000 INR","Indoor Stadium","24th Sep 2016","1 PM to 5 PM","Anand K","9449340844","A Regular quiz based on anything and everything. As IoT is inextricable linked to every-thing, there is a need to know about the things which involve IoT in general. This general perspective for novices in IoT is served in this quizzing format."));
        eventArrayList.add(new Event(86,"Pictonnect (in collaboration with Mech)","Telecommunication",false,"100/Team of 2","1000 INR","500 INR","EC 207","24th Sep 2016","10 AM to 4 PM","Sarayu M","9880106670","In collaboration with Mechanical department. How well are you being updated to the current trends and applications of IOT technology advancements.? Come test and update yourselves. Pictonnect will consist all of it with a twist. Team of two will participate in two rounds. In the first round guess the word Related to IOT  with the pictures shown. First ten teams will be selected to the second round , in which the output and input to a system is to be given  through the keywords guessed found in round one."));
        eventArrayList.add(new Event(87,"Project J","Telecommunication",false,"300/Team of 3","1000 INR","700 INR","AC lab, telecom dept","23rd Sep 2016","10 AM to 5 PM","Rohini Raj","8553578476",""));
        eventArrayList.add(new Event(88,"App Development","Electronics & Intrumentation",false,"500/team of 3","3000 INR","2000 INR","nan","nan","nan","Anusha K G","8892963124","Team of 3. Teams will be given electronic junk. They have to come out with a working IOT related device using the Junk. Details of the junk provided will be intimidated 1 week prior to event to all registrants."));
        eventArrayList.add(new Event(89,"IOT TECHNIQUES, IMPLEMENTATION USING ARDUINO","Electronics & Intrumentation",false,"750/Team of 3","2000 INR","1000 INR","nan","nan","nan","Sarika J","9611591382","•IoT applications using sensors.\n" +
                "•Using IoT technologies to improve industrial requirement ,with specialized focus on the areas of industries, media, IT, and networks.\n" +
                "•To learn how IOT it is useful in social cause like using connectivity to address poverty, human rights and climate change.\n" +
                "Teams of  3  members"));
        eventArrayList.add(new Event(90,"PROJECT DISPLAY ON HOME AUTOMATION","Electronics & Intrumentation",false,"200/Team","3000 INR","2000 INR","IT Classroom 2","Special","Special","Chetna B","9880928324","Participants will demonstrate and showcase their project.Evaluation of the project will be done by the industrial representative.Use the knowledge of sensors and various communication protocols. Use the concept for their mini / major projects multi\u00ADdisciplinary areas.Application of IOT"));
        eventArrayList.add(new Event(92,"Buoyant","Electronics & Intrumentation",false,"300/Team of 2","2000 INR","1000 INR","IT Classroom 3","23rd Sep 2016","10 AM to 4 PM","Ashwin","9743067056","Single Round To Keep Thermocol And Cardboard Floating And Be Able To Move Through a given path using own methods.The model should hold good for buoyancy principle. Should only use thermocol and dc motor. Should move in the given track. Good design . Teams of 2."));


        EventAdapter eventAdapter = new EventAdapter(getContext(), eventArrayList);
        listView.setAdapter(eventAdapter);

        listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long l) {
                Intent intent = new Intent(getActivity(), EventDetails.class);
                intent.putExtra("details", eventArrayList.get(position));
                getActivity().startActivity(intent);
            }
        });

        return rootview;
    }
}
